### ISSUE TITLE
Variance of power spectrum

### ISSUE THREAD

**Issue by Kojobu** [21cmfast/py21cmFAST-tools#6]
Greetings!

I want to do parameter inference using chi2 loss.

In the original powerbox library one can set a as an argument (get_variance) which, if True, also returns the variance estimation of the power spectrum. Since the code of py21cmFAST-tools is based on powerbox, it would be very useful if this feature would be considered as important for future updates.

Best 
Kojobu

**Comment by DanielaBreitman** [comment]
Hi @Kojobu, I added get_variance in PR #7 . Can you check that it has the functionality that you want and let me know?
Thanks.

**Comment by Kojobu** [comment]
Looking good! I'll append some test plots, thanks for implementing it! 

The lightcone I used for testing:
![lightcone](https://github.com/user-attachments/assets/625df82d-09f0-4683-a056-185b26c11d26)

1D power spectrum:
![1d_ps](https://github.com/user-attachments/assets/c4e4ac1a-abbd-49f0-a862-f09af2516cd7)
![var_1d_ps](https://gith
![power_vs_variance_1d_ps](https://github.com/user-attachments/assets/43dbd9ba-3eea-4e9a-be6e-84de5c692072)
ub.com/user-atta


2D power spectrum:
![2d_ps](https://github.com/user-attachments/assets/7d331e12-25b8-4dc4-b33e-0463ef7ec279)
![power_vs_variance_2d_ps](https://github.com/user-attachments/assets/6d7739e5-93b4-40ed-91bc-a51ea04e6fd1)
chments/assets/f153d1d8-38a8-406f-917e-f38a6fef1e0b)
![power_vs_variance_1d_ps](https://github.com/user-attachments/assets/da8288e9-b6f8-4d12-9110-880f62ad52c6)

**Comment by DanielaBreitman** [comment]
Hey @Kojobu, it's done, can you run your tests again? I will add tests and merge it to main afterward.
Thanks!!

**Comment by Kojobu** [comment]
I did run the tests, looking really good! I'll append the same analysis down below (binning is 10 this time for better visibility). Thank you, it's much appreciated!

![lightcone](https://github.com/user-attachments/assets/913298dc-a019-4cee-9421-e30aefeda93a)
![1d_ps](https://github.com/user-attachments/assets/5a117b31-22ef-4ea1-9f72-89b68dabaf6b)
![var_1d_ps](https://github.com/user-attachments/assets/b0cef5e8-8f1a-44d4-a64c-d5191bb7e14d)
![power_vs_variance_1d_ps](https://github.com/user-attachments/assets/a087e44e-3f9a-4104-be2f-04035d252e84)
![2d_ps](https://github.com/user-attachments/assets/cd3fb378-2374-4bd9-bf1f-f838d028436c)
![var_2d_ps](https://github.com/user-attachments/assets/b611b9e0-852e-4648-98b5-15f582d14523)
![power_vs_variance_2d_ps](https://github.com/user-attachments/assets/62b03610-2916-49a0-9386-a846734e1751)

**Comment by Kojobu** [comment]
I also found a small bug in the general code:
When computing the 2D power spectrum with 
```log_bins=False```, the k_perp bins are linearly spaces but the k_parallel bins were computed as log bins.

**Comment by Kojobu** [comment]
And another small bug I found in the general code:
When setting the argument ```log_bins=False``` the kpar bins are still in log although they should be linearly spaced.

**Comment by DanielaBreitman** [comment]
Right, that's because if you don't want the kpar in log, you should just turn off the postprocessing altogether. I'll make that clearer in the code. Thank you!!
